# Generated by Django 5.2.5 on 2026-02-13 17:39

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DetectionHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="uploads/")),
                ("detected_objects", models.TextField()),
                ("audio_file", models.FileField(upload_to="audio/")),
                ("date", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
